# This software is Copyright (C) 2004-2008  Bristol University
# and is released under the GNU General Public License version 2.

all:

tidy:
	-mv *.log ../tmp/
	-mv *.prof ../tmp/

clean:
	-rm *~ *.pyc *.pyo

real_clean:	tidy clean
	-rm *.pol *.vpol

